on:
  pull_request: {}
  push:
    branches: master

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: oxidecomputer/actions-rs_toolchain@master
        with:
            override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

#       - uses: actions-rs/cargo@v1
#         with:
#           command: clippy
#           args: -- -D warnings
